FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://*:5001
EXPOSE 5001
WORKDIR /app
COPY --from=base /app/out .
ENTRYPOINT ["dotnet", "GraphQL.NET.dll", "--launch-profile Prod"]